# -*- coding: utf-8 -*-
"""AI_Image_Segmentation_Studio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10sNSgnffRLqVZ7MFnOPRZW4z5343Wz69
"""

import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import layers, Model
print("TensorFlow:", tf.__version__)
print("TFDS:", tfds.__version__)

dataset, info = tfds.load("oxford_iiit_pet", with_info=True, as_supervised=False)
print("Dataset downloaded successfully!")
print(info)

print(dataset.keys())

print("Training Samples:", info.splits["train"].num_examples)
print("Testing Samples:", info.splits["test"].num_examples)

sample = next(iter(dataset["train"]))
print(sample.keys())

plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.imshow(sample["image"])
plt.title("Original Image")
plt.axis("off")
plt.subplot(1, 2, 2)
plt.imshow(sample["segmentation_mask"][:, :, 0],cmap="gray")
plt.title("Segmentation Mask")
plt.axis("off")
plt.show()

IMG_HEIGHT = 128
IMG_WIDTH = 128
BATCH_SIZE = 16
EPOCHS = 20

def preprocess(data):

    image = data["image"]
    mask = data["segmentation_mask"]
    image = tf.image.resize( image, [IMG_HEIGHT, IMG_WIDTH] )
    mask = tf.image.resize( mask,  [IMG_HEIGHT, IMG_WIDTH],  method="nearest" )
    image = tf.cast(image, tf.float32) / 255.0
    mask = tf.cast(mask, tf.int32)
    mask = tf.where( mask == 2, 1, 0 )
    mask = tf.cast( mask,  tf.float32 )
    return image, mask

train_raw = dataset["train"]
test_raw = dataset["test"]

train_dataset = train_raw.map(preprocess, num_parallel_calls=tf.data.AUTOTUNE)
test_dataset = test_raw.map(  preprocess,  num_parallel_calls=tf.data.AUTOTUNE)

TOTAL_TRAIN = info.splits["train"].num_examples
train_size = int(0.8 * TOTAL_TRAIN)
train_dataset = train_dataset.shuffle( TOTAL_TRAIN, seed=42, reshuffle_each_iteration=False)
validation_dataset = train_dataset.skip(train_size)
train_dataset = train_dataset.take(train_size)

train_dataset = train_dataset.batch( BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
validation_dataset = validation_dataset.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
test_dataset = test_dataset.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

images, masks = next(iter(train_dataset))
print("Images Shape:", images.shape)
print("Masks Shape:", masks.shape)

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.imshow(images[0])
plt.title("Input Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow( masks[0][:, :, 0],cmap="gray")
plt.title("Binary Ground Truth")
plt.axis("off")
plt.show()

def conv_block(x, filters):

    x = layers.Conv2D( filters, 3, padding="same", activation="relu" )(x)
    x = layers.BatchNormalization()(x)
    x = layers.Conv2D(  filters, 3,  padding="same",  activation="relu" )(x)
    x = layers.BatchNormalization()(x)
    return x

def build_unet():

    inputs = layers.Input( shape=(IMG_HEIGHT, IMG_WIDTH, 3))
    c1 = conv_block(inputs, 32)
    p1 = layers.MaxPooling2D((2, 2))(c1)
    c2 = conv_block(p1, 64)
    p2 = layers.MaxPooling2D((2, 2))(c2)
    c3 = conv_block(p2, 128)
    p3 = layers.MaxPooling2D((2, 2))(c3)
    c4 = conv_block(p3, 256)
    p4 = layers.MaxPooling2D((2, 2))(c4)
    c5 = conv_block(p4, 512)
    u6 = layers.Conv2DTranspose( 256, 2, strides=2, padding="same")(c5)
    u6 = layers.concatenate([u6, c4])
    c6 = conv_block(u6, 256)
    u7 = layers.Conv2DTranspose( 128, 2, strides=2, padding="same" )(c6)
    u7 = layers.concatenate( [u7, c3])
    c7 = conv_block(u7, 128)
    u8 = layers.Conv2DTranspose( 64, 2, strides=2, padding="same")(c7)
    u8 = layers.concatenate( [u8, c2] )
    c8 = conv_block(u8, 64)
    u9 = layers.Conv2DTranspose( 32, 2, strides=2, padding="same" )(c8)
    u9 = layers.concatenate( [u9, c1] )
    c9 = conv_block(u9, 32)
    outputs = layers.Conv2D( 1, 1, activation="sigmoid")(c9)
    model = Model( inputs=inputs, outputs=outputs, name="Oxford_Pet_UNet" )
    return model

model = build_unet()
model.summary()

def dice_coefficient(y_true, y_pred):

    smooth = 1e-6

    y_true = tf.cast(y_true,  tf.float32)
    y_pred = tf.cast( y_pred, tf.float32 )
    y_true = tf.reshape( y_true, [-1] )
    y_pred = tf.reshape( y_pred, [-1])
    intersection = tf.reduce_sum( y_true * y_pred)
    dice = (2.0 * intersection + smooth) / (tf.reduce_sum(y_true) + tf.reduce_sum(y_pred) + smooth )
    return dice

def iou_metric(y_true, y_pred):

    smooth = 1e-6

    y_true = tf.cast(  y_true, tf.float32)
    y_pred = tf.cast( y_pred > 0.5, tf.float32)
    intersection = tf.reduce_sum( y_true * y_pred )
    union = (tf.reduce_sum(y_true) + tf.reduce_sum(y_pred) - intersection )iou = ( intersection + smooth) / ( union + smooth)
    return iou

def dice_loss(y_true, y_pred):
    return 1.0 - dice_coefficient( y_true, y_pred )

def combined_loss(y_true, y_pred):
    bce = tf.keras.losses.binary_crossentropy( y_true, y_pred )
    bce = tf.reduce_mean(bce)
    dice = dice_loss( y_true, y_pred )
    return bce + dice

model.compile(
    optimizer=tf.keras.optimizers.Adam(
        learning_rate=1e-4
    ),
    loss=combined_loss,
    metrics=[
        dice_coefficient,
        iou_metric
    ]
)

print("Model compiled successfully!")

callbacks = [

    tf.keras.callbacks.ModelCheckpoint(
        "best_oxford_pet_unet.keras",
        monitor="val_dice_coefficient",
        mode="max",
        save_best_only=True,
        verbose=1 ),

    tf.keras.callbacks.EarlyStopping(
        monitor="val_dice_coefficient",
        mode="max",
        patience=5,
        restore_best_weights=True,
        verbose=1 ),

    tf.keras.callbacks.ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=2,
        verbose=1 )
]

history = model.fit(
    train_dataset,
    validation_data=validation_dataset,
    epochs=EPOCHS,
    callbacks=callbacks
)

plt.figure(figsize=(8, 5))
plt.plot( history.history["loss"],  label="Training Loss")
plt.plot( history.history["val_loss"], label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.show()

plt.figure(figsize=(8, 5))
plt.plot( history.history["dice_coefficient"], label="Training Dice" )
plt.plot(history.history["val_dice_coefficient"], label="Validation Dice" )
plt.xlabel("Epoch")
plt.ylabel("Dice Score")
plt.title("Dice Coefficient")
plt.legend()
plt.show()

plt.figure(figsize=(8, 5))
plt.plot( history.history["iou_metric"], label="Training IoU" )
plt.plot( history.history["val_iou_metric"], label="Validation IoU")
plt.xlabel("Epoch")
plt.ylabel("IoU")
plt.title("Intersection over Union")
plt.legend()
plt.show()

results = model.evaluate(test_dataset, verbose=1)
print("\nTest Results")
print("Loss:", results[0])
print("Dice:", results[1])
print("IoU:", results[2])

def predict_image(image):
    input_image = tf.expand_dims(image, axis=0 )
    prediction = model.predict( input_image, verbose=0 )[0]
    probability_mask = prediction[:, :, 0]
    binary_mask = (probability_mask > 0.5).astype(np.uint8)
    return probability_mask, binary_mask

test_image, test_mask = next(iter(test_dataset.unbatch()))
predicted_probability, predicted_mask = predict_image( test_image)

plt.figure(figsize=(16, 5))
plt.subplot(1, 4, 1)
plt.imshow(test_image)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 4, 2)
plt.imshow(test_mask[:, :, 0],cmap="gray")
plt.title("Ground Truth")
plt.axis("off")

plt.subplot(1, 4, 3)
plt.imshow(predicted_probability,cmap="gray")
plt.title("Prediction Probability")
plt.axis("off")

plt.subplot(1, 4, 4)
plt.imshow(predicted_mask,cmap="gray")
plt.title("Final Segmentation")
plt.axis("off")
plt.show()

plt.figure(figsize=(6, 6))
plt.imshow(test_image)
plt.imshow(predicted_mask, alpha=0.4, cmap="jet")
plt.title("Segmentation Overlay")
plt.axis("off")
plt.show()

samples = test_dataset.unbatch().take(5)
plt.figure(figsize=(15, 15))
for i, (image, mask) in enumerate(samples):
    predicted_probability, predicted_mask = predict_image( image)

    plt.subplot(5, 3, i * 3 + 1)
    plt.imshow(image)
    plt.title("Original")
    plt.axis("off")

    plt.subplot(5, 3, i * 3 + 2)
    plt.imshow(mask[:, :, 0], cmap="gray")
    plt.title("Ground Truth")
    plt.axis("off")

    plt.subplot(5, 3, i * 3 + 3)
    plt.imshow(  predicted_mask,  cmap="gray")
    plt.title("Prediction")
    plt.axis("off")

plt.tight_layout()
plt.show()

model.save(
    "oxford_pet_unet.keras"
)

print("Model saved successfully!")





